- pom.xml
- src/main/c/netty_io_uring_linuxsocket.c
- src/main/c/netty_io_uring_native.c
Motivation:
We just merged some changes into netty that needs some changes to be
able to compile this project
Modifications:
- Add -ldl to ldflags
- Adjust jni code to use the new utils
Result:
Be able to compile again
> Adjust to compile against latest netty snapshot

- .github/workflows/codeql-analysis.yml
Motivation:
We should make use of codeql code scanning.
Modification:
Add config for code scanning.
Result:
Scan code on each commit
> Add codeql-analysis.yml 

- README.md
Motivation:
We had multiple reports from people that tried to use io_uring but did not notice that it failed due memlock settings. Let's make it more clear how to solve the problem
Modifications:
Add section about memlock
Result:
Hopefully its easier for people to understand why using of io_uring failed
> Make it more clear that you may need to adjust memlock limits

- .github/workflows/ci-main.yml
- docker/docker-compose.centos-6.18.yaml
- docker/docker-compose.centos-6.yaml
- pom.xml
Motivation:
We should enable leak detection when building PRs.
Modifications:
- Add profile to make it easy to enable leak detection
- Enable leak detection for pull requests
Result:
Easier to find leaks
> Enable leak detection when building PRs.

- pom.xml
Motivation:
We only updated the netty version, we should do the same for tcnative
Modifications:
Update to latest release
Result:
Use latest tcnative version during tests
> Update to latest tcnative version

- docker/docker-compose.centos-7.yaml
- pom.xml
Motivation:
Let's use the latest hawtjni plugin and let us share most of the build configuration
Modifications:
- Update to latest plugin
- Share build configuration
Result:
Fixes https://github.com/netty/netty-incubator-transport-io_uring/issues/66
> Update to latest hawtjni plugin and share build configuration

- pom.xml
Motivation:
There was a new release of the plugin
Modifications:
Update to 1.7.0
Result:
> Update to latest os-maven-plugin

- .github/scripts/git_checkout_release_tag.sh
- .github/scripts/merge_local_staging.sh
- .github/workflows/ci-release.yml
- docker/docker-compose.centos-6.18.yaml
- docker/docker-compose.centos-6.yaml
- docker/docker-compose.centos-7.yaml
Motivation:
Doing releases manually is error-prone, it would be better if we could do it via a workflow
Modification:
- Add workflow to cut releases
- Add related scripts
- Adjust docker-compose file for staging releases
Result:
Be able to easily cut a release via a workflow
> Add workflow to cut releases

- pom.xml
Motivation:
Update to latest netty version
Modifications:
Depend on altest version
Result:
> A new netty release is out

- src/main/c/netty_io_uring_native.c
- src/main/java/io/netty/incubator/channel/uring/CmsgHdr.java
- src/main/java/io/netty/incubator/channel/uring/IOUringDatagramChannel.java
- src/main/java/io/netty/incubator/channel/uring/IOUringSegmentedDatagramPacket.java
- src/main/java/io/netty/incubator/channel/uring/MsgHdr.java
- src/main/java/io/netty/incubator/channel/uring/MsgHdrMemory.java
- src/main/java/io/netty/incubator/channel/uring/Native.java
- src/main/java/io/netty/incubator/channel/uring/NativeStaticallyReferencedJniMethods.java
- src/test/java/io/netty/incubator/channel/uring/IOUringDatagramUnicastTest.java
Motivation:
We should also support GSO when usiing io_uring for maximum performance
Modifications:
- Add code to support GSO
- Add unit test
Result:
Support GSO
> Add support for UDP_SEGMENT (GSO)

- src/main/c/netty_io_uring_native.c
Motivation:
We did miss some function declarations to support static compilation.
Modifications:
- Added needed function declarations
Result:
Be able to support static compilation
> Add the ability to static compile

- pom.xml
Upgrade to the latest version of Netty
> Upgrade from Netty 4.1.62.Final to 4.1.63.Final

- pom.xml
Motivation:
Another day another netty release. Let's update
Modifications:
Update to netty 4.1.65.Final
Result:
> Update to netty 4.1.65.Final

- src/main/java/io/netty/incubator/channel/uring/AbstractIOUringChannel.java
Some clean ups for AbstractIOUringChannel
> Some cleanups

- src/main/java/io/netty/incubator/channel/uring/IOUring.java
Motivation:
When invoking `IOUring#isAvailable` the exception below is thrown. This is a regression made with #97
```
java.lang.ExceptionInInitializerError
at io.netty.incubator.channel.uring.IOUring.<clinit>(IOUring.java:27)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:264)
at reactor.netty.resources.DefaultLoopIOUring.<clinit>(DefaultLoopIOUring.java:95)
at reactor.netty.resources.DefaultLoopNativeDetector.<clinit>(DefaultLoopNativeDetector.java:32)
at reactor.netty.resources.LoopResources.hasNativeSupport(LoopResources.java:270)
...
Caused by: java.lang.IllegalStateException: Only supported on Linux
at io.netty.incubator.channel.uring.Native.loadNativeLibrary(Native.java:277)
at io.netty.incubator.channel.uring.Native.<clinit>(Native.java:69)
... 106 …
```
> Ensure IOUring#isAvailable does not throw Exception

- pom.xml
Motivation:
We should use an more up-to-date version of ant to fix a possible CVE
Modifications:
Upgrade ant
Result:
Use more recent ant version
> Upgrade ant

- pom.xml
Motivation:
A new netty-build was released
Modifications:
Update to latest release
Result:
> Update to latest netty-build

- pom.xml
Motivation:
New netty release is out
Modifications:
Upgrade to 4.1.72.Final
Result:
> Update to netty 4.1.72.Final

- pom.xml
Motivation:
There was a new netty release
Modifications:
Update to latest netty version
Result:
> Update to netty 4.1.73.Final

- docker/Dockerfile.centos6
- docker/Dockerfile.centos7
- docker/docker-compose.centos-6.18.yaml
- docker/docker-compose.centos-7.yaml
Motivation:
There are new java version
Modifications:
- Switch to sdkman
- Update all java versions to latest patch release
Result:
Use latest java versions on the CI
> Update java versions

- pom.xml
Motivation:
There were new release of netty and netty-tcnative
Modifications:
Update to latest releases
Result:
Use latest releases
> Update to latest netty / netty-tcnative releases

- transport-native-io_uring/src/main/c/netty_io_uring_native.c
Motivation:
This is a pretty common issue, and our error message can do more to help guide people toward a resolution.
Modification:
If we can't create the ring due to ENOMEM, then have the error message mention to people that they should check their memlock limit, since that's the most common cause of that error.
Result:
More helpful error message and hopefully lessened support burden for us.
> Improve error message when we can't create the ring due to memlock limit

- pom.xml
Motivation:
A new netty release is out
Modifications:
Update to 4.1.75.Final
Result:
> Update to netty 4.1.75.Final

- pom.xml
Motivation:
We release a new netty-tcnative version
Modifications:
Upgrade to 2.0.51.Final
Result:
> Upgrade netty-tcnative version

- transport-native-io_uring/src/test/java/io/netty/incubator/channel/uring/IOUringRemoteIpTest.java
Motivation:
Some address families might not be supported by the host that runs the testsuite
Modifications:
Don't fail testsuite if address family is not supported
Result:
testsuite pass again
> Don't fail testsuite if address family is not supported

- .github/workflows/ci-build.yml
- .github/workflows/ci-deploy.yml
- .github/workflows/ci-pr.yml
- .github/workflows/ci-release.yml
- .github/workflows/codeql-analysis.yml
Motivation:
We should set some MAVEN_OPTS related to retries etc to make the build more stable
Modifications:
Add MAVEN_OPTS
Result:
More stable builds
> Set retries to make build more stable

- docker/docker-compose.centos-6.18.yaml
Motivation:
There was a new java 8 release
Modifications:
Update to 8.0.332-zulu
Result:
Build with latest java8 release
> Update to 8.0.332-zulu

- .github/workflows/ci-deploy.yml
- .github/workflows/ci-pr.yml
- .github/workflows/ci-release.yml
Motivation:
ubuntu-18.04 is deprecated. Let's just use ubuntu-latest
Modifications:
Use ubuntu-latest in workflows
Result:
Cleanup
> Use ubuntu-latest in workflows

- pom.xml
Motivation:
There were new releases, let's upgrade
Modifications:
Update dependencies
Result:
Use latest releases
> Upgrade to latest netty and netty-tcnative releases

- .mvn/wrapper/maven-wrapper.properties
- docker/Dockerfile.centos6
- docker/Dockerfile.centos7
- docker/Dockerfile.centos7arm64v8
Motivation:
Let's use the latest maven version to build
Modifications:
Upgrade to 3.9.0
Result:
Use latest maven release
> Update maven to 3.9.0

- pom.xml
Motivation:
We should depend on the latest releases
Modifications:
Update dependencies
Result:
Use up-to-date dependencies
> Update to latest netty / netty-tcnative release

- docker/docker-compose.centos-6.18.yaml
- docker/docker-compose.centos-7.yaml
- docker/docker-compose.centos-7arm.yaml
Motivation:
There are new releases of java.
Modifications:
Upgrade java versions to latest release
Result:
Use latest versions on the CI
> Upgrade java versions

- pom.xml
Motivation:
A new version was released
Modifications:
Update to latest release
Result:
Use latest version as dependency
> Upgrade netty to latest version

- transport-classes-io_uring/src/main/java/io/netty/incubator/channel/uring/IOUringEventLoopGroup.java
- transport-classes-io_uring/src/main/java/io/netty/incubator/channel/uring/Native.java
Also fixed a typo in the constant name (system property name was correct), and added a short explanation.
Fixes #230
> Change default of iosqeAsyncThreshold to Integer.MAX_VALUE

- pom.xml
Motivation:
A new netty release is out
Modifications:
Update to 4.1.111
Result:
Use latest netty release
> Update to netty 4.1.111

- pom.xml
Motivation:
We released a new netty version
Modifications:
Update to 4.1.117.Final
Result:
> Update to netty 4.1.117.Final
