netty/netty-incubator-transport-io_uring

- docker/Dockerfile.centos
- docker/README.md
- docker/docker-compose.centos-6.18.yaml
- docker/docker-compose.yaml
Motivation:
Add docker files that can be used to setup the right env to compile the transport. This can also be used to release as it will ensure we link against the minimum GLIBC version and so make it usable everywhere as long as a recent enough kernel is present.
Modifications:
Add docker files
Result:
Be able to compile easily and release
> Add docker files to compile io_uring transport

- README.md
Stable kernel 5.9 is released and we should update it in README.
> Update minimum kernel version

- src/main/java/io/netty/incubator/channel/uring/IOUringServerSocketChannel.java
- src/test/java/io/netty/incubator/channel/uring/IOUringRemoteIpTest.java
Motivation:
We passed the wrong memory address to the method that did read the
remote address of the accepted sockets which lead to bogus addresses.
Modifications:
- Pass in the correct memory address
- Add unit test
Result:
Fixes https://github.com/netty/netty-incubator-transport-io_uring/issues/10
> Correctly obtain the remote address of accepted sockets

- src/main/java/io/netty/incubator/channel/uring/IOUringServerSocketChannel.java
- src/main/java/io/netty/incubator/channel/uring/SockaddrIn.java
- src/test/java/io/netty/incubator/channel/uring/IOUringRemoteIpTest.java
Motivation:
We we bind the socket to an ipv4 address we also should always return an
ipv4 address
Modifications:
Keep track of if we bind to ipv4 and if so convert ipv6-mapped-ipv4
addressed to Inet4Address
Result:
Fixes https://github.com/netty/netty-incubator-transport-io_uring/issues/18
> Handle ipv6-mapped-ipv4 in a consistent way with epoll transport

- src/main/java/io/netty/incubator/channel/uring/IOUringEventLoop.java
- src/main/java/io/netty/incubator/channel/uring/IOUringServerSocketChannel.java
- src/main/java/io/netty/incubator/channel/uring/MsgHdrMemory.java
- src/main/java/io/netty/incubator/channel/uring/SockaddrIn.java
- src/test/java/io/netty/incubator/channel/uring/IOUringRemoteIpTest.java
- src/test/java/io/netty/incubator/channel/uring/SockaddrInTest.java
Motivation:
#21 tried to fix the handling of ipv6-mapped-ipv4 addresses but did not fix all cases.
Modifications:
- Correctly detect mapped addresses in all cases
- Add more unit tests
Result:
Fixes https://github.com/netty/netty-incubator-transport-io_uring/issues/18 for real
> Correctly handle mapped addresses in all cases

- docker/Dockerfile.cross_compile_aarch64
- docker/docker-compose.yaml
- pom.xml
Motivation:
To make it easier to support aarch64 we should include a profile and docker file that can be used to cross-compile.
Modification:
Add needed profile and docker file.
Result:
Be able to cross compile for aarch64 . Fixes #26.
Co-Authored-by: Norman Maurer <norman_maurer@apple.com>
> Add aarch64 profile and Docker files

- src/main/java/io/netty/incubator/channel/uring/IOUringEventLoop.java
- src/main/java/io/netty/incubator/channel/uring/IOUringSubmissionQueue.java
Motivation:
it actually makes no sense to use IOSQE_ASYNC, as eventfd is used to wakeup io_uring_enter
Modifications:
add new eventfd read method in SubmissionQueue
Result:
https://github.com/netty/netty-incubator-transport-io_uring/issues/14 fixed
> Remove eventfd read async flag

- .github/workflows/ci.yml
- docker/docker-compose.centos-6.18.yaml
- docker/docker-compose.yaml
Motivation:
We should deploy snapshots whenever we build the main branch
Modifications:
- Add config for docker compose to be able to deploy
- Use secrets to setup settings.xml
Result:
Automatically deploy snapshots
> Deploy snapshots when build the main branch (#55)

- .github/workflows/ci-build.yml
Motivation:
We should fail the build when a leak was detected
Modifications:
Add extra step which will fail the job when a leak was found
Result:
Leaks will fail the job
> Fail job if leak was detected

- src/main/java/io/netty/incubator/channel/uring/IOUringEventLoopGroup.java
Motivation:
We need to ensure we force the JNI initialization when the
IOUringEventLoopGroup is loaded. Otherwise things will fail if we didnt
do it outself.
Modifications:
Call IOUring to force JNI init.
Result:
Fixes https://github.com/netty/netty-incubator-transport-io_uring/issues/47
> Force JNI initialization when IOUringEventLoopGroup is loaded

- .github/scripts/check_leak.sh
- .github/workflows/ci-pr.yml
Motivation:
We should better use seperate workflows for PR and normal builds
Modifications:
- Split workflows
- Better cache reuse
Result:
Cleanup
> Split pr and normal build

- .github/workflows/ci-deploy.yml
- docker/docker-compose.centos-6.18.yaml
- docker/docker-compose.centos-6.yaml
- docker/docker-compose.centos-7.yaml
Motivation:
We need to take special care when deploying snapshots as we need to generate the jars in multiple steps
Modifications:
- Use the nexus staging pluging to stage jars locally in multiple steps
- Add extra job that will merge these staged jars and deploy these
Result:
Correctly deploy for all archs
> Correctly deploy artifacts that are build on different archs (#10893)

- pom.xml
Motivation:
4.1.47.Final is out, we should replace our SNAPSHOT dependency
Modifications:
Update to non SNAPSHOT release
Result:
Don't depend on SNAPSHOT
> Update to netty 4.1.47.Final

- src/main/java/io/netty/incubator/channel/uring/IOUringSubmissionQueue.java
Motivation:
The `InternalLogger.trace()` uses a formatted `String` and `Object` as an arguments, so if we pass a primitive type (e.g. int) it will be autoboxed to `java.lang.Integer`.
Modifications:
Add additional check `isTraceEnabled` before call logger to avoid unnecessary allocation. 
Result:
Fixes: #61
> Add check isTraceEnabled for avoid unnecessary object allocation

- .github/workflows/ci-pr.yml
Motivation:
To make it easier to understand why the build fails lets use an action that will report which unit test failed
Modifications:
- Replace custom script with action-surefire-report
Result:
Easier to understand test failures
> Use action to report unit test errors

- .github/workflows/ci-pr.yml
Motivation:
It turns out we can't use the action to check for build failures as it can't be used when a PR is done from a fork. Let's just use our simple script.
Modifications:
- Replace action with custom script
Result:
Builds for PRs that are done via forks work again.
> Use custom script to check for build failures

- .github/workflows/ci-pr-reports.yml
- .github/workflows/ci-pr.yml
Motivation:
To make it easier to understand why a build failed let us publish the rest results
Modifications:
Use a new workflow to be able to publish the test reports
Result:
Easier to understand why a PR did fail
> Publish test results after PR run

- src/main/c/netty_io_uring_native.c
- src/main/java/io/netty/incubator/channel/uring/IOUringDatagramChannel.java
- src/main/java/io/netty/incubator/channel/uring/IOUringSubmissionQueue.java
- src/main/java/io/netty/incubator/channel/uring/Native.java
- src/main/java/io/netty/incubator/channel/uring/NativeStaticallyReferencedJniMethods.java
- src/test/java/io/netty/incubator/channel/uring/IOUringDatagramUnicastTest.java
Motivation:
io_uring has a bug which lead to the situation that it not correctly
respect the non-blocking nature of a fd and so may block on recvmsg
forever.
Modifications:
- Workaround said bug by using MSG_DONTWAIT
- Correctly continue reading until we shouldnt
- Add unit test
Result:
io_uring works for DatagramChannels as expected
> Use MSG_DONTWAIT to workaround io_uring bug with datagrams

- src/main/java/io/netty/incubator/channel/uring/IOUringEventLoop.java
Motivation:
Sometimes a user may want to explicit force the submission of the IO.
Modifications:
- Make IOUringEventLoop public
- Expose IOUringEventLoop.submitIO
Result:
User is able to submit IO
> Expose IOUringEventLoop.submitIO()

- docker/Dockerfile.centos7
- docker/docker-compose.centos-7.yaml
- pom.xml
Motivation:
LSE (https://mysqlonarm.github.io/ARM-LSE-and-MySQL/) can have a huge performance difference. Let's ensure we use a compiler that can support it.
Modifications:
Update to gcc10 when cross-compiling as it supports LSE and enables it by default
Result:
More optized builds for aarch64
> Let's use gcc10 when cross-compiling for LSE support

- docker/docker-compose.centos-6.18.yaml
Motivation:
We should use the latest java version when building on the CI
Modifications:
Update java version
Result:
> Update java version

- .github/workflows/ci-build.yml
- .github/workflows/ci-deploy.yml
- .github/workflows/ci-pr.yml
- docker/docker-compose.centos-6.yaml
- docker/docker-compose.centos-7.yaml
Motivation:
To reduce the likelyness of build failures due network problems it is best to cache maven dependencies.
Modifications:
- Correctly mount .m2/repository
- Use action for caching
Result:
More stable builds
> Use maven dependency caching

- src/main/java/io/netty/incubator/channel/uring/Native.java
Motivation:
It turns out it is quite easy to cause a classloader deadlock in more recent java updates if you cause classloading while you are in native code. Because of this we should just workaround this issue by pre-load all the classes that needs to be accessed in the OnLoad function.
Modifications:
- Preload all classes that would otherwise be loaded by native OnLoad functions.
Result:
Workaround for https://github.com/netty/netty/issues/11209 and https://bugs.openjdk.java.net/browse/JDK-8266310
> Preload classes before calling native OnLoad function to prevent class loader deadlock

- .github/config/meta-data
- .github/config/user-data
- .github/scripts/build_kernel.sh
- .github/scripts/build_qemu_image.sh
- .github/scripts/check_build_result.sh
- .github/scripts/check_leak.sh
- .github/scripts/merge_local_staging.sh
- .github/scripts/qemu_build.exp
- .github/scripts/release_checkout_tag.sh
- .github/scripts/release_rollback.sh
- .github/workflows/ci-build.yml
- .github/workflows/ci-deploy.yml
- .github/workflows/ci-pr-reports.yml
- .github/workflows/ci-pr.yml
- .github/workflows/ci-release.yml
- .github/workflows/codeql-analysis.yml
Motivation:
We should have license header whenever possible.
Modifications:
Add header to scripts and workflow config
Result:
More clear licensing
> Add license header to our scripts and workflows

- .github/scripts/qemu_build.exp
- .github/workflows/ci-deploy.yml
- .github/workflows/ci-pr.yml
- .github/workflows/ci-release.yml
- .github/workflows/codeql-analysis.yml
- docker/docker-compose.centos-6.yaml
- docker/docker-compose.centos-7.yaml
Motivation:
When Maven does not run in batch mode, it will continuously print its progress as it downloads dependencies.
This can produce a very large amount of log output, that makes it harder to debug build failures.
Modification:
- Make all Maven builds run in batch mode by adding the -B command line flag.
- Some builds were already running batch mode but had the flag in a different location – these have had their -B flag moved so all builds are consistent.
- Add -ntp flag
Result:
Much less output in our build logs where Maven is just downloading stuff.
> Make build log output less chatty

- pom.xml
- src/test/java/io/netty/incubator/channel/uring/IOUringDatagramUnicastTest.java
- src/test/java/io/netty/incubator/channel/uring/IOUringSocketConditionalWritabilityTest.java
- src/test/java/io/netty/incubator/channel/uring/IOUringSocketHalfClosedTest.java
- src/test/java/io/netty/incubator/channel/uring/IOUringSocketShutdownOutputBySelfTest.java
- src/test/java/io/netty/incubator/channel/uring/IOUringSocketSslClientRenegotiateTest.java
- src/test/java/io/netty/incubator/channel/uring/IOUringSocketSslEchoTest.java
- src/test/java/io/netty/incubator/channel/uring/IOUringSocketSslGreetingTest.java
- src/test/java/io/netty/incubator/channel/uring/IOUringSocketSslSessionReuseTest.java
- src/test/java/io/netty/incubator/channel/uring/IOUringSocketStartTlsTest.java
Hello, I just saw this morning this [(Pull Request)](https://github.com/netty/netty-incubator-transport-io_uring/pull/110)
I made this PR to try to fix the test since netty has changed JUnit version that add TestInfo and other change.
Based on Epoll test for the setupClientChannel part
Hope it will help.
> Fix netty test 4.1.68

- .mvn/wrapper/maven-wrapper.properties
Motivation:
The tree includes 'Maven Wrapper' with settings such that it downloads Maven 3.8.1 from the ASF 'backup' distribution servers, rather than the main distribution mirrors, or more typically in the wrappers case actually Maven Central (which it seems the settings did use prior to the last config update). As the CI jobs are grabbing Maven several times for every commit, plus adding on any related use from peoples Netty forks/downloads etc, this will add up. It would be good to direct them elsewhere.
Modifications:
Change url
Result:
Less load on the apache backup download server
> change mvnw distributionUrl to use Google mirror of central

- pom.xml
- transport-native-io_uring/pom.xml
- transport-native-io_uring/src/test/java/io/netty/incubator/channel/uring/IOUringDatagramUnicastTest.java
Motivation:
We did miss to update the dependencies when upgrading to junit 5 so the tests did not run anymore
Modifications:
Remove junit4 dependencies
Result:
junit tests run again
> Fix dependencies so junit5 tests are run

- pom.xml
- transport-native-io_uring/pom.xml
Motivation:
We need to include bouncycastle as test dependency as otherwise we will fail when trying to run the testsuite on more recent JDKs
Modifications:
Add bouncycastle as test dependency
Result:
Be able to run testsuite on more recent JDKs
> Include bouncycastle as test dependency

- transport-native-io_uring/src/main/c/netty_io_uring_native.c
Motivation:
Some functions in netty_io_uring_native.c are local to the file
but not declared as static.
Modifications:
- make file local functions static
Result:
File local function access limited to the file they are
defined in.
> Make file local functions static

- transport-native-io_uring/src/test/java/io/netty/incubator/channel/uring/IOUringSocketSslGreetingTest.java
Motivation:
In one class we still used @BeforeClass while we should have used @BeforeAll. This caused the method to never been executed and so could lead to failures.
Modifications:
Replace @BeforeClass with @BeforeAll
Result:
Build fails no-more
> Use correct junit5 annotation to execute before method

- pom.xml
- transport-native-io_uring/pom.xml
- transport-native-io_uring/src/test/java/io/netty/incubator/channel/uring/IOUringAndEpollTest.java
Motivation:
We should add a test to ensure that its possible to have the native io_uring transport and the native epoll transport on the same classpath and load them.
Modifications:
- Add test dependency on native epoll transport
- Add test case
Result:
Ensure both transports can exist on the classpath without problems
> Add test that native io_uring and native epoll transport can co-exist

- transport-native-io_uring/pom.xml
Motivation:
We need to add a Fragment-Host entry to the manifest for the jars that contain the native libs so its possible to use these in OSGI.
Modifications:
Add Fragment-Host entry to manifest.
Result:
Be able to use via OSGI
> Add Fragment-Host declaration to bundles shipping native libs

- transport-classes-io_uring/src/main/java/io/netty/incubator/channel/uring/IOUring.java
- transport-classes-io_uring/src/main/java/io/netty/incubator/channel/uring/Native.java
- transport-native-io_uring/src/test/java/io/netty/incubator/channel/uring/NativeTest.java
Motivation:
By default we not try to use io_uring when the kernel is < 5.9. While this is a good default there might be sitations when the user still wants to try using it, for example if another kernel is used but io_uring was backported
Modifications:
Add io.netty.transport.uring.enforceKernelVersion property which can be used to control enforcement of kernel version (default is true).
Result:
Allow to use io_uring even if the kernel not matches requirements
> Allow to enforce io_uring usage

- transport-classes-io_uring/src/main/java/io/netty/incubator/channel/uring/Native.java
Motivation:
We used .uring. in the system properties but it should be .iouring. to be consistent
Modifications:
Fix property names
Result:
Correct naming
> Fix typos in system properties

- transport-classes-io_uring/src/main/java/io/netty/incubator/channel/uring/Native.java
- transport-native-io_uring/src/main/c/netty_io_uring_native.c
- transport-native-io_uring/src/test/java/io/netty/incubator/channel/uring/NativeTest.java
Motivation:
We did leak a file during our tests and also during the initial loading of the native lib
Modifications:
Use a tempory file / directory and so ensure the file is deleted
Result:
No leaked file
> Don't leak temporary file during test and inital loading of lib.

- pom.xml
Motivation:
We should use the latest netty-tcnative release in tests
Modifications:
Upgrade version
Result:
> Update netty-tcnative-boringssl-static to latest version

- .github/workflows/ci-pr-reports.yml
- .github/workflows/ci-pr.yml
Motivation:
Github uses a recent enough kernel these days to run io_uring
Modifications:
Remove qemu usage and just run the tests directly
Result:
Faster testing
> We don't need qemu anymore as github CI uses a recent enough kernel

- transport-classes-io_uring/src/main/java/io/netty/incubator/channel/uring/IOUringDatagramChannel.java
- transport-classes-io_uring/src/main/java/io/netty/incubator/channel/uring/MsgHdrMemory.java
- transport-classes-io_uring/src/main/java/io/netty/incubator/channel/uring/SockaddrIn.java
Motivation:
We need to correctly handle zero-size datagram packets
Modifications:
Ensure we correctly detect zero-size datagram packets
Result:
Testsuite passes again
> Correctly handle zero size datagram packets

- Makefile
- docker/Dockerfile.centos7arm64v8
- docker/docker-compose.centos-7arm.yaml
- transport-native-io_uring/pom.xml
Motivation:
We're increasingly developing on MacOS/M1 machines, so it's useful to have a standard set-up for building and testing locally.
Modification:
Add another set of docker files for building native ARM (not cross-compiling) binaries. Add a Makefile to make it easy to start these builds or drop into the docker guest shell.
Result:
Easier development flow when working on a MacOS/M1 machine.
> Add build files for MacOS/M1

- .github/workflows/ci-build.yml
- .github/workflows/ci-deploy.yml
- .github/workflows/ci-pr.yml
- .github/workflows/ci-release.yml
- .github/workflows/codeql-analysis.yml
Motivation:
The workflow files need to know to build the netty5 branch as one of the mainline branches
Modification:
Change `main` for `netty5` in the workflow files.
Result:
Hopefully the builds are picked up now.
> Enable workflows on the netty5 branch

- pom.xml
- transport-classes-io_uring/pom.xml
- transport-native-io_uring/pom.xml
Motivation:
The modules and deliverables produces by the Netty 5 port needs to have separate maven coordinates from the Netty 4.1 version.
Modification:
Change maven artifact names to reflect that they're intended for Netty 5 integration.
Result:
Netty 5 and 4.1 versions can coexist in Maven (but currently still clash in their native library names)
> Change maven module and artifact names

- pom.xml
- transport-native-io_uring/pom.xml
Motivation:
We can use the Java 8 version of BouncyCastle now.
Modification:
Upgrade BouncyCastle to version 1.71.1 and switch to the Java 8 supporting variants.
Result:
Newer BouncyCastle.
> Upgrade BouncyCastle

- pom.xml
Motivation:
A new netty release is out
Modifications:
Upgrade to 4.1.84.Final
Result:
Use latest netty release
> Upgrade to netty 4.1.84.Final

- transport-native-io_uring/src/main/c/netty5_io_uring_native.c
Motivation:
Looks like older kernels do not have MSG_FASTOPEN. We should still be able to compile on such kernels, even if io_uring won't work there.
Modification:
Define MSG_FASTOPEN if it isn't already.
Result:
We can compile on older kernels that don't have MSG_FASTOPEN.
> Define MSG_FASTOPEN for older kernels

- transport-classes-io_uring/src/main/java/io/netty/incubator/channel/uring/AbstractIOUringChannel.java
- transport-classes-io_uring/src/main/java/io/netty/incubator/channel/uring/IOUring.java
- transport-classes-io_uring/src/main/java/io/netty/incubator/channel/uring/IOUringChannelOption.java
- transport-classes-io_uring/src/main/java/io/netty/incubator/channel/uring/IOUringServerSocketChannel.java
- transport-classes-io_uring/src/main/java/io/netty/incubator/channel/uring/IOUringServerSocketChannelConfig.java
- transport-classes-io_uring/src/main/java/io/netty/incubator/channel/uring/IOUringSocketChannelConfig.java
- transport-classes-io_uring/src/main/java/io/netty/incubator/channel/uring/IOUringSubmissionQueue.java
- transport-classes-io_uring/src/main/java/io/netty/incubator/channel/uring/Native.java
- transport-classes-io_uring/src/main/java/io/netty/incubator/channel/uring/NativeStaticallyReferencedJniMethods.java
- transport-native-io_uring/src/main/c/netty_io_uring_native.c
- transport-native-io_uring/src/test/java/io/netty/incubator/channel/uring/IOUringSocketTestPermutation.java
Motivation:
We support TCP_FAST_OPEN in our other transports so we should also support it when using io_uring
Modifications:
Add code to support TCP_FAST_OPEN to be on-par with other transports
Result:
Support TCP_FAST_OPEN for server and client side when using io_uring
> Add support for client / server side TCP_FAST_OPEN

- transport-classes-io_uring/src/main/java/io/netty/incubator/channel/uring/MsgHdrMemoryArray.java
- transport-native-io_uring/src/test/java/io/netty/incubator/channel/uring/MsgHdrMemoryArrayTest.java
Motivation:
We did a mistake while calculate the maximum number of hdrs and so always returned 1 less then possible.
Modifications:
Fix calculation and add unit test
Result:
Be able to use all hdrs
> Correctly handle nextHdr() so we not return null to early

- transport-classes-io_uring/src/main/java/io/netty/incubator/channel/uring/IOUringSubmissionQueue.java
Currently it isn't possible to test the IORING_OP_NOP because the enqueSqe method is private. This PR fixes that by making it package private.
> Make submissionqueue enqueueSqe method package private.

- transport-classes-io_uring/src/main/java/io/netty/incubator/channel/uring/AbstractIOUringStreamChannel.java
- transport-classes-io_uring/src/main/java/io/netty/incubator/channel/uring/IOUringDatagramChannel.java
- transport-classes-io_uring/src/main/java/io/netty/incubator/channel/uring/IOUringEventLoop.java
- transport-classes-io_uring/src/main/java/io/netty/incubator/channel/uring/IOUringSubmissionQueue.java
- transport-classes-io_uring/src/main/java/io/netty/incubator/channel/uring/Native.java
- transport-classes-io_uring/src/main/java/io/netty/incubator/channel/uring/NativeStaticallyReferencedJniMethods.java
- transport-native-io_uring/src/main/c/netty_io_uring_native.c
- transport-native-io_uring/src/test/java/io/netty/incubator/channel/uring/NativeTest.java
Motivation:
Recv/Send paths are more suited for socket fds
Modifications:
Replace existing READ/WRITE OP usages with RECV/SEND
Result:
Better performance
> Replace stdlib write/read with send/recv

- transport-classes-io_uring/src/main/java/io/netty/incubator/channel/uring/IOUringEventLoop.java
Motivation:
fd reuse can replace a closed channel, still awaiting POLL_REMOVE CQEs, with a new one that will handle them, causing its removal from the map of handled channels.
Modification:
POLL_REMOVE CQEs are handled only by (marked) closed fds. Opened one, will just ignore them.
Result:
No still opened (reused) fds can be removed due to a late POLL_REMOVE completion arrival.
> Ignore POLL_REMOVE CQEs on opened fd (Fixes #194)

- transport-classes-io_uring/src/main/java/io/netty/incubator/channel/uring/AbstractIOUringChannel.java
- transport-native-io_uring/src/test/java/io/netty/incubator/channel/uring/IOUringClientSocketConnectionShortTimeoutTest.java
Motivation:
uncompleted CONNECT_SCHEDULE prevent force closing and issuing IORING_OP_CLOSE, causing a graceful shutdown to complete its quiet period and ignore any later CONNECT completion (at the mercy of OS configuration for connect timeout) due to already shutdown executor.
This will cause the executor to not be able to complete its cleanup because of unclosed channels and making it to hang awaiting an already happened CQE.
Modification:
Allow force close to initiate a close despite the uncompleted CONNECT_SCHEDULE, allowing it to issue a IORING_OP_CLOSE. When the FD close would complete, a later CQE of CONNECT_SCHEDULE on the closed FD will be ignored because its channel is already deregistered.
Result:
Prompt channel close on short timeout (regardless peer presence)
> Event Loop shutdown stuck due to uncompleted connect (Fixes #192)

- transport-native-io_uring/pom.xml
Motivation:
We need to provide different Automatic-Module-Name entries for different architectures so you can import all of them
Modifications:
Add os / arch infos to the Automatic-Module-Name
Result:
Be able to use with java modules
> Fix Automatic-Module-Name

- .mvn/wrapper/maven-wrapper.properties
- docker/Dockerfile.centos6
- docker/Dockerfile.centos7
- docker/Dockerfile.centos7arm64v8
Motivation:
There was a new maven release we should use. Also just use sdkman to do so.
Modifications:
- Upgrade to maven 3.9.1
- Use sdkman
Result:
Use latest maven version and use sdkman
> Upgrade to latest maven version and use sdkman to install it

- pom.xml
Motivation:
There was a new release of netty and netty-tcnative
Modifications:
Use latest releases
Result:
Up to date dependencies
> Upgrade netty and netty-tcnative to latest releases

- pom.xml
Motivation:
A new version of netty is out
Modifications:
Upgrade to 4.1.94.Final
Result:
Use latest netty version
> Upgrade to netty 4.1.94.Final

- .github/workflows/ci-build.yml
- .github/workflows/ci-deploy.yml
- .github/workflows/ci-pr.yml
- .github/workflows/ci-release.yml
- .github/workflows/codeql-analysis.yml
Motivation:
When caching fails during workflow execution we should still continue the build as its just an optimization. Also we should use the new fork for docker layer caching
Modifications:
- Update action that does the docker layer caching to the new fork
- Ignore errors during caching
Result:
More stable builds
> Update workflows to make things more robust when it comes to caching

- transport-native-io_uring/pom.xml
Motivation:
We should run our testsuite with '-Xcheck:jni' to ensure we catch bugs in our JNI code which could later cause issues like crashes
Modifications:
- Add -Xcheck:jni
Result:
Testsuite will be able to catch more JNI bugs
> Use '-Xcheck:jni' during testsuite run to detect JNI bugs

- docker/docker-compose.centos-6.18.yaml
- docker/docker-compose.centos-7.yaml
- docker/docker-compose.centos-7arm.yaml
Motivation:
We didnt use the latest java releases on the CI
Modifications:
Update java releases
Result:
Use latest java releases on the CI
> Upgrade java versions to latest patch release

- transport-classes-io_uring/pom.xml
- transport-native-io_uring/pom.xml
Motivation:
Some tools depend on the Specification-* entries in the MANIFEST.MF. Unfortunaly
we don't add these at the moment
Modifications:
Configure plugin to also add the Specification-* entries
Result:
MANIFEST.MF contains Specification-* entries
> Also add Specification-* entries to MANIFEST.MF

- .github/workflows/ci-build.yml
- .github/workflows/ci-deploy.yml
- .github/workflows/ci-pr-reports.yml
- .github/workflows/ci-pr.yml
- .github/workflows/ci-release.yml
Motivation:
We should keep our actions up to date.
Modifications:
Upgrade all github actions to latest releases
Result:
Housekeeping
> Update github actions to latest versions

- transport-classes-io_uring/src/main/java/io/netty/incubator/channel/uring/AbstractIOUringChannel.java
Motivation:
Whe using io_uring we can in fact cancel a connect() operation by just closing the underyling fd.
Modifications:
Don't mark the promise as uncancellable before issue the non-blocking connect() call Add comment to explain code
Result:
Related to https://github.com/netty/netty/issues/13843 and https://github.com/netty/netty/pull/13849
> Allow to cancel connect() operations when using io_uring

- transport-classes-io_uring/src/main/java/io/netty/incubator/channel/uring/IOUring.java
The method is checking the io_uring availability, not the epoll availability. This likely happened because the method got copy-pasted from the Epoll class.
> Fix javadoc typo

- transport-classes-io_uring/src/main/java/io/netty/incubator/channel/uring/IOUringEventLoop.java
- transport-classes-io_uring/src/main/java/io/netty/incubator/channel/uring/IOUringSubmissionQueue.java
- transport-classes-io_uring/src/main/java/io/netty/incubator/channel/uring/Native.java
- transport-classes-io_uring/src/main/java/io/netty/incubator/channel/uring/NativeStaticallyReferencedJniMethods.java
- transport-native-io_uring/src/main/c/netty_io_uring_native.c
- transport-native-io_uring/src/test/java/io/netty/incubator/channel/uring/NativeTest.java
I had a memory issue and @franz1981 suggested #211 as the cause. This patch is my fix for that bug, though I don't believe my mem issue was ultimately caused by this.
This PR does the legwork for adding ioringOpTimeoutRemove, and implementing a test. However two things can still be improved:
> Remove old timeout when deadline changes

- transport-classes-io_uring/src/main/java/io/netty/incubator/channel/uring/IOUringEventLoop.java
Motivation:
We need to catch exceptions from event completions, like epoll and kqueue does. Otherwise the exceptions can propagate to the event loop thread and kill it. This makes it appear stuck or shut down.
Modification:
Catch and log exceptions thrown by IOUringEventLoop.handle.
Result:
The event loop should not get stuck or shut down when a completion event throws an exception.
> Catch completion handler errors

- pom.xml
Motivation:
A new netty release is out
Modifications:
Update to 4.1.110
Result:
Use latest netty release
> Update to netty 4.1.110

- docker/docker-compose.centos-6.18.yaml
- docker/docker-compose.centos-7.yaml
- docker/docker-compose.centos-7arm.yaml
Motivation:
The used java versions in our docker-compose file were outdated
Modifications:
Update all versions to latest release
Result:
Use latest versions on CI
> Update java versions to latest release

- docker/Dockerfile.centos7
- docker/Dockerfile.centos7arm64v8
Motivation:
We can't use the default mirrorlist anymore as it will fail and so fail the docker build
Modifications:
Use baseurl with the correct vault
Result:
Docker image can be build again
> Replace usage of mirrorlist with baseurl

- docker/docker-compose.centos-6.yaml
- docker/docker-compose.centos-7.yaml
This ports over the changes from https://github.com/netty/netty/pull/14203, which makes the tests run in the docker containers again.
> Port netty seccomp changes

- .devcontainer/ubuntu/Dockerfile
- .devcontainer/ubuntu/devcontainer.json
Motivation:
Linux is the most important deployment OS, but a significant amount of development takes place on Windows and MacOS. Devcontainers allow developers to quickly spin up a Docker container, to run their IDE inside a native Linux environment. This is helpful for debugging and testing.
Intellij IDEA Ultimate and Visual Studio Code both have support for devcontainers.
Modifications:
Add devcontainer spec file for ubuntu
Result:
It's now possible to run an IDE in a Linux devcontainer environment on Windows and MacOS.
> Add devcontainers for Linux

- docker/Dockerfile.centos6
- docker/Dockerfile.centos7
- docker/Dockerfile.centos7arm64v8
Motivation:
We should explicit specify the platform we use for docker to ensure our build produce the correct artifacts
Modifications:
Add --platform=linux/amd64 to docker files
Result:
Ensure build produces correct artifacts
> Explicit specify the platform for Docker files

- pom.xml
Motivation:
We use an outdated netty version
Modifications:
Update to latest netty version
Result:
> Update to netty 4.1.116.Final (#767)

- transport-classes-io_uring/src/main/java/io/netty/incubator/channel/uring/IOUringSubmissionQueue.java
Motivation:
Sometimes submission of ops will fail if these are executed inline and return some error. This is expected and so we shouldn't log a warn message. That said it might still be useful to log these cases with trace level.
Modifications:
Log submission failures via tracing level
Result:
Use correct logging level that will not confuse people. This is a port of https://github.com/netty/netty/pull/14671
> Log submission failures via tracing level as these are expected

- transport-classes-io_uring/src/main/java/io/netty/incubator/channel/uring/IOUringSubmissionQueue.java
Motivation:
We did not correctly fill the submission entry for IORING_OP_TIMEOUT which could lead to timeouts firing to early. We need to use a count of 1 when submitting these as we want to notify once either there is one completion ready to process or when the timeout elapsed.
Modifications:
Correctly fill submission entry
Result:
IoUringEventLoop.run() will block for the correct amount of time. 
This is a port of https://github.com/netty/netty/pull/14712
> Fix SubmissionQueue.addTimeout(...)
